version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  tts:
    <<: *restart_policy
    container_name: tts

    build:
      context: ./tts/.
      dockerfile: Dockerfile

    ports:
      - 5002:5002

    networks:
        - ai

  backend:
    <<: *restart_policy
    container_name: backend
    build:
      context: ./backendv2/.
      dockerfile: Dockerfile

    environment:
      - GEMINI_API_KEY=API_KEY


    depends_on:
      - tts

    networks:
        - ai

    ports:
      - 3000:3000


  frontend:
    <<: *restart_policy
    container_name: frontend

    build:
      context: ./frontend/.
      dockerfile: Dockerfile

    tty: true


    networks:
      - ai

    depends_on:
      - backend

    ports:
      - 80:5173



networks:
    ai:
        name: ai

